version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
        API_SECRET: ${API_SECRET}
    container_name: api-container-tech2
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - API_SECRET=${API_SECRET}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

 
